### ISSUE TITLE
How can I enable Debug messages?

### ISSUE THREAD

**Issue by Nols1000** [syb0rg/Khronos#17]
My problem right know is getting alsa devices working on ubuntu. Therefor I would like to get the debug messages. How can I enable it.

**Comment by syb0rg** [comment]
By running `cmake -DDEBUG=1 ..` before the build, debug messages will be output.  When I get around to logging they'll be enabled by default and just output to the log file.

As for the ALSA devices, installing `libasound2-dev` may solve your problem.  I've already identified this issue and am working on it, as CMake fails to find the default ALSA libraries.  However, fixing this problem in PortAudio2 creates issues with the libraries depending on it... so it's taking longer to rollout a satisfactory fix.
