### ISSUE TITLE
Missing dependencies on Ubuntu

### ISSUE THREAD

**Issue by ShipsWithCannons** [syb0rg/Khronos#7]
On Ubuntu, the following dependencies are required and not installed by default:
- autoconf
- libtool
- automake
- bison
- swig

All of those can be installed using `apt` and their existence should be checked at the start of the build process.

**Comment by Vogel612** [comment]
assuming apt for installation is probably not a good idea. This excludes other linux-distros such as CentOS (using yum) or arch (using pacman).

**Comment by syb0rg** [comment]
It also excludes OSX and Windows systems.

**Comment by ShipsWithCannons** [comment]
@Vogel612 I'm simply speaking from the Ubuntu view here. I agree a more general approach should be taken, but let's fix one thing at a time. IIUC OSX and Windows are already functioning.

**Comment by syb0rg** [comment]
For now, it's easiest to install these manually.  I'm going to reconsider the software relying on these dependencies (sphinxbase and pocketsphinx), and evaluate if it is better to continue supporting them in this project or abandon them for a better option.

**Comment by syb0rg** [comment]
These dependencies have been taken care of with 68a0e7024741d6deaac006291c164733418c9427, and should no longer be needed.
